export const acessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikx1aXMgQmFydWZpIiwiZW1haWwiOiJsdWlzLmJhcnVmaUBnbWFpbC5jb20iLCJpYXQiOjE3MTEyOTc4MjksImV4cCI6MTcxMTkwMjYyOSwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjEifQ.4OSbN9dQ9j8GUAClZOkv1hUSl8AkPrgmzXtkS-dIgXI';
